default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: rails-mister-cocktail-2_development

test:
  <<: *default
  database: rails-mister-cocktail-2_test
